- name: Create Azure Resources
  hosts: all
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: AzureResources-rg
      location: centralindia
  - name: Create a storage account
    azure_rm_storageaccount:
      resource_group: AzureResources-rg
      name: 5avm4d4okvdlq4jz65404id
      type: Standard_RAGRS
  - name: Create a log profile
    azure_rm_monitorlogprofile:
      name: myProfile
      location: centralindia
      locations:
        - centralindia
      categories:
        - Write
        - Action
      retention_policy:
        enabled: True
        days: 45
      storage_account:
        resource_group: AzureResources-rg
        name: 5avm4d4okvdlq4jz65404id
    register: output
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: AzureResources-rg
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: AzureResources-rg
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: AzureResources-rg
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: AzureResources-rg
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: AzureResources-rg
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: AzureResources-rg
      name: centosvm
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Rishabh@123
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
