- name: Create Azure Resources
  hosts: all
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: AzureResources-rg
      location: centralindia
  - name: Create a storage account
    azure_rm_storageaccount:
      resource_group: AzureResources-rg
      name: 5avm4d4okvdlq4jz65404id
      type: Standard_RAGRS
