- name: Create Azure Resources
  hosts: all
  tasks:
  - name: Create a log profile
    azure_rm_monitorlogprofile:
      name: myProfile
      location: centralindia
      locations:
        - centralindia
      categories:
        - Write
        - Action
      retention_policy:
        enabled: False
        days: 45
      storage_account:
        resource_group: AzureResources-rg
        name: 5avm4d4okvdlq4jz65404id
    register: output
